### ISSUE TITLE
missing scematic

### ISSUE THREAD

**Issue by hsk-dk** [o0shojo0o/PixelIt#1]
Would it be possible to add the scematic to the repository?

**Comment by o0shojo0o** [comment]
I'll have to take a look at how I file these. 
Currently it can be found here: [Wiki](https://wiki.dietru.de/books/pixel-it/chapter/hardware)

**Comment by hsk-dk** [comment]
thanks, the wiki wasn't working for me earlier, but the problem has resolved it self.
