### ISSUE TITLE
Wrong Color

### ISSUE THREAD

**Issue by bug84** [o0shojo0o/PixelIt#102]
Hi, I have configurate an wemos d1 mini with an 8x32matrix.
It works nice, but the colors don’t match. If I make orange oder Brown, it shows me red or nothing.
I also tested the bitmaps in the library, same error. Also testet in options all possible configs without success.

**Comment by o0shojo0o** [comment]
What power supply do you use?

**Comment by bug84** [comment]
I have found the error. Can be closed.
