### ISSUE TITLE
text position is ignored with bitmaps wider than 8 Pixel

### ISSUE THREAD

**Issue by lubeda** [o0shojo0o/PixelIt#114]
text position is ignored with bitmaps wider than 8 Pixel
Scrolling makes it even worse.

See my sample json:
`{
  "text": {
    "textString": "long text",
    "scrollText": "auto",
    "position": { "x": 15, "y": 1 },
    "hexColor": "#FFFFFF"
  },
  "bitmap": {
    "position": { "x": 0, "y": 0 },
    "size": { "width": 14, "height": 8 },
    "data": [
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 51461, 51461, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 17289, 7063, 7063, 17289, 17289, 51461, 17289, 7063, 7063,
      7063, 7063, 7063, 17289, 17289, 17289, 7063, 7063, 17289, 51461, 51461,
      51461, 7063, 17289, 7063, 7063, 7063, 17289, 17289, 17289, 7063, 7063,
      7063, 17289, 51461, 17289, 17289, 17289, 17289, 7063, 7063, 7063, 17289,
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289,
      17289, 17289, 17289, 17289, 17289, 17289, 17289, 17289
    ]
  }
}`

**Comment by o0shojo0o** [comment]
Yes, currently only 8x8 or 8x32 pixel are supported.
