### ISSUE TITLE
feature request: updates to internal clock

### ISSUE THREAD

**Issue by poblabs** [o0shojo0o/PixelIt#119]
Hi, looking to see if a couple of updates can be added to the internal clock?

I'm in USA, so our locale is a bit different than what's default.

1. Can an option be added to adjust date format? Like `MM/DD` instead of `DD.MM.`?
2. We start our week on Sunday. Can an option be added to have a toggle to start week on Sunday?

Thanks!

**Comment by o0shojo0o** [comment]
Hi @poblabs, 
yes those are good points, back when I built the PixelIt for myself I just ignored them. 
As soon as I can find the time I will take a look at it.
