### ISSUE TITLE
Documentation site is not accessible

### ISSUE THREAD

**Issue by dragospascale** [o0shojo0o/PixelIt#123]
The data folder is empty so how to upload the web interface ? 
When requesting "/" (root) I get empty page

**Comment by dragospascale** [comment]
In fact the page is not empty and in console I get 
GET http://docs.bastelbunker.de/PixelIt/new_webif/css/app.879fa878.css net::ERR_NAME_NOT_RESOLVED
which in fact is the same problem with inaccessible site docs.bastelbunker.de
Why an application for a microcontroller must depend on an external internet site ?

**Comment by o0shojo0o** [comment]
quite simply it is too big ... 
And the data is on GitHub (GitHub Pages)
https://github.com/o0shojo0o/PixelIt/tree/master/docs/new_webif
