### ISSUE TITLE
BUG: Bootloop on Auto brightness "to lux" values lower than 1

### ISSUE THREAD

**Issue by Kugelfang666** [o0shojo0o/PixelIt#125]
Hi, 

I'm playing with my PixelIT trying to get the Autorbrightness feature up an running. I found that if I set a value lower than 1 as "to lux" (e.g. 0,5) it makes the ESP go into a boot loop. The only way to recover is a clean flash and then re-flashing with the PixelIT firmware. The issue is fully reproducible on my system.

**Comment by oli-19** [comment]
i can confirm this issue
