### ISSUE TITLE
BUG: Webinterface not loading on Safari

### ISSUE THREAD

**Issue by Kugelfang666** [o0shojo0o/PixelIt#127]
I'm encountering an issue where the PixelIT web interface does not load on Safari (iPad or Mac). Clearing the cache helps fixing the issue temporarily. When I checked the console I found this:

![Bildschirmfoto 2022-01-26 um 07 33 17](https://user-images.githubusercontent.com/3289654/151114704-59480a40-db72-4b0a-b272-d45ad1ce884c.png)

Other browsers like chrome do not encounter this problem. I'm running he lasted FW 0.3.16

**Comment by o0shojo0o** [comment]
I only have iPhones here at hand and they do not cause any problems. 
However, this problem seems to occur only on Apple devices.

**Comment by rliegmann** [comment]
I have a Mac with Safari and there I don't get a single error message in the console.
I just googled the error message. Maybe this helps [here](https://support.apple.com/de-de/HT203370).

**Comment by o0shojo0o** [comment]
I have now changed the DNS entries and "Optimized", I hope that now the problem is solved.

**Comment by Kugelfang666** [comment]
sorry I must have overlooked this, will test and report back if this issue is solved now
