### ISSUE TITLE
Issues starting with es32 d1 mini - Wifimanager

### ISSUE THREAD

**Issue by diogopms** [o0shojo0o/PixelIt#128]
Issues starting wifimanager on esp32 device

```
*wm:[1] AutoConnect 
*wm:[2] ESP32 event handler enabled 
*wm:[2] Connecting as wifi client... 
*wm:[2] setSTAConfig static ip not set, skipping 
*wm:[1] No wifi saved, skipping 
*wm:[2] Connection result: WL_NO_SSID_AVAIL
*wm:[1] AutoConnect: FAILED 
*wm:[2] Starting Config Portal 
*wm:[2] Disabling STA 
*wm:[2] Enabling AP 
*wm:[1] StartAP with SSID:  PIXEL_IT
*wm:[2] AP has anonymous access! 
[  9678][E][WiFiGeneric.cpp:983] mode(): Could not set mode! 12289
[  9684][E][WiFiAP.cpp:118] softAP(): enable AP first!
*wm:[0] [ERROR] There was a problem starting the AP 
*wm:[1] AP IP address:
[1970-01-01T00:00:10] Hotspot: Waiting for WiFi configuration
*wm:[1] Starting Web Portal 
*wm:[2] HTTP server started 
*wm:[2] Config Portal Running, blocking, waiting for clients... 
*wm:[2] Portal Timeout In 180 seconds
*wm:[2] Portal Timeout In 159 seconds
```

Version:
```sh
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 34:ab:95:fb:9d:8c
```

![image](https://user-images.githubusercontent.com/2445019/151164390-3b836865-29b8-4451-90fa-36217300cabd.png)

**Comment by diogopms** [comment]
Update: If i comment the Wifimanager i was able to enter in the dashboard.


![image](https://user-images.githubusercontent.com/2445019/151204455-77642025-6333-431b-a9b9-774ef8c104a2.png)

**Comment by o0shojo0o** [comment]
Again, I can't say much about this as I don't use esp32 .
@rliegmann maybe?

**Comment by rliegmann** [comment]
Hey diogopms,
I'll take a look right away.
I was even able to reproduce the error. I'll report when I have something new.
LG rliegmann

**Comment by rliegmann** [comment]
UPDATE:
For a quick fix or test, can you please insert the following line in front of the WifiManager and transfer it?

`WiFi.mode(WIFI_AP);`

I also noticed that the WiFi stuff doesn't work properly when using the serial port via USB. So flash it and then operate it on a USB power supply and see if the WiFi shows up.
If that works, I would adjust the project configuration file for your board.

LG eliegmann
