### ISSUE TITLE
Save config is not working for ESP32

### ISSUE THREAD

**Issue by diogopms** [o0shojo0o/PixelIt#129]
The Saveconfigs is not working on ESP32

![image](https://user-images.githubusercontent.com/2445019/151205958-0e840662-2858-4d57-93df-5d5a38396529.png)

Version:
```sh
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 34:ab:95:fb:9d:8c
```

```sh
/#/:1 Uncaught SyntaxError: Unexpected token } in JSON at position 10
    at JSON.parse (<anonymous>)
    at t.value (build.js:1)
    at t.value (build.js:1)
    at WebSocket.forEach.t.WebSocket.<computed> (build.js:1)
```

**Comment by o0shojo0o** [comment]
Sorry can not say much about it, I do not use esp32.
@rliegmann can you say something about it?

**Comment by rliegmann** [comment]
Yes, I might be able to help here too. I had that problem a long time ago too. 
The whole thing has something to do with the SPIFFS memory. For some reason the ESP cannot initialize the memory properly. I could solve the problem by simply transferring the example Scatch (SPIFFS_Test.ino) from the Arduino library to the ESP. This will take a read and write test. Then simply iron over the Pixel IT firmware again and it should work.

LG rliegmann
