### ISSUE TITLE
2 pieces of 8*32

### ISSUE THREAD

**Issue by liv-in-sky** [o0shojo0o/PixelIt#132]
hi - I like your project - I'm using iobroker

my question: is it somehow possible to add a second matrix in a row and controll it with your software - so we could use 8*64

thanx

**Comment by liv-in-sky** [comment]
got he answer there https://github.com/o0shojo0o/PixelIt/discussions/75

**Comment by StuartHaire** [comment]
@liv-in-sky did you find a way to chain more matrixes together?

**Comment by liv-in-sky** [comment]
> @liv-in-sky did you find a way to chain more matrixes together?

sorry - I didn't pursue it further
