### ISSUE TITLE
only 4 leds on

### ISSUE THREAD

**Issue by sander816** [o0shojo0o/PixelIt#147]
i am new to pixel it.
I have 8x32 led matrix, trhis one:
https://nl.aliexpress.com/item/33018815831.html?gatewayAdapt=glo2nld&spm=a2g0o.9042311.0.0.27424c4dvlK0EP

i flashed pixelit on a esp12-f. Connected 5v and gnd to led matrix, and d2 on the esp to D-in.
Esp is loading on the ip adress it has, but i only see 4 leds on the matrix that are on.

what am i doing wrong?

**Comment by o0shojo0o** [comment]
Which firmware did you use?

**Comment by o0shojo0o** [comment]
Yes that's what I was getting at, try the **firmware_ESP8266.bin** from here https://github.com/o0shojo0o/PixelIt/releases

**Comment by sander816** [comment]
well, thats what i used already.
I meant regarding hardware

Op wo 2 mrt. 2022 om 10:45 schreef Dennis Rathjen ***@***.***

**Comment by sander816** [comment]
and just tested the matrix with another controller, they are working fine

Op wo 2 mrt. 2022 om 10:56 schreef sander kerkhoff ***@***.***>:

**Comment by o0shojo0o** [comment]
Yes this could be a problem, if the power supply fluctuates this can even go to a crash
