### ISSUE TITLE
Wrong DST

### ISSUE THREAD

**Issue by miccgn** [o0shojo0o/PixelIt#148]
My PixelIts have decided: it's summertime!
I checked: the DSToffset() routine in Tools.h indeed says: yes, it is DST!
Seems like the formula is wrong.

Quickfix: disable DST in Options.

**Comment by hamster65** [comment]
same here, I noticed it just now for the first time. And there is no option to select a time zone.. hm.

**Comment by Rushmed** [comment]
Same here, neded to disable DST to get the correct hour shown.

**Comment by o0shojo0o** [comment]
Fixed by v0.3.17
