### ISSUE TITLE
Can't change wifi or reset

### ISSUE THREAD

**Issue by rozza-m** [o0shojo0o/PixelIt#172]
I moved my PixelIt to a different AP (but the same SSID) - doesn't connect.
So I tried to re-associate and re-connect the wifi again - there is no method to do so.
So I tried to factory reset - again - there is no method to do this.

Feels like at least a "reset to defaults" should be available?

**Comment by rozza-m** [comment]
N.b. it seems like esp WiFi manager or firmware is pretty basic with WiFi roaming between multiple APs with the same SSID or else this wouldn't be a problem 🙁 https://esp32.com/viewtopic.php?t=3885

**Comment by o0shojo0o** [comment]
![image](https://user-images.githubusercontent.com/19333515/169660770-ee1aba9b-5d0b-4ae2-891b-cfa601f615cd.png)

**Comment by rozza-m** [comment]
😱 Amazing!

**Comment by rozza-m** [comment]
@o0shojo0o that was amazingly fast work, thanks. I'll try it out when the WebUI updates.

**Comment by o0shojo0o** [comment]
If you want to test it in advance you can compile the new firmware and start the WebUi via the DevServer. 
https://github.com/o0shojo0o/PixelIt/wiki/Develop-on-WebUI

**Comment by rozza-m** [comment]
Thanks 
![image](https://user-images.githubusercontent.com/1784953/169694507-007f48f8-2986-40f1-8e8c-f7a48badbd87.png)
Is this the IP of the PixelIt or the dev server?

**Comment by o0shojo0o** [comment]
IP of the PixelIt 😊
